INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK]?  There''s an app for that.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Why can''t I sleep at night?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s that smell?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I got 99 problems but [BLANK] ain''t one.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Maybe she''s born with it.  Maybe it''s [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s the next Happy Meal&copy; toy?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Anthropologists have recently discovered a primitive tribe that worships [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('It''s a pity that kids these days are all getting involved with [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('During Picasso''s often-overlooked Brown Period, he produced hundreds of paintings of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Alternative medicine is now embracing the curative powers of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s that sound?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What ended my last relationship?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('MTV''s new reality show features eight washed-up celebrities living with [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I drink to forget [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I''m sorry professor, but I couldn''t complete my homework because of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What is Batman''s guilty pleasure?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('This is the way the world ends <br> This is the way the world ends <br> Not with a bang but with [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s a girl''s best friend?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('TSA guidelines now prohibit [BLANK] on airplanes.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK].  That''s how I want to die.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In the new Disney Channel Original Movie, Hannah Montana struggles with [BLANK] for the first time.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What does Dick Cheney prefer?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Dear Abby, I''m having some trouble with [BLANK] and would like your advice.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Instead of coal, Santa now gives the bad children [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s the most emo?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In 1,000 years when paper money is but a distant memory, [BLANK] will be our currency.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s the next superhero/sidekick duo?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('A romantic, candlelit dinner would be incomplete without [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK].  Becha can''t have just one!');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('White people like [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK].  High five, bro.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Next from J.K. Rowling: Harry Potter and the Chamber of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('BILLY MAYS HERE FOR [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('War!  What is it good for?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('During sex, I like to think about [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What are my parents hiding from me?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What will always get you laid?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In L.A. County Jail, word is you can trade 200 cigarettes for [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What did I bring back from Mexico?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What don''t you want to find in your Chinese food?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What will I bring back in time to convince people that I am a powerful wizard?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('How am I maintaining my relationship status?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK].  It''s a trap!');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Coming to Broadway this season, [BLANK]: The Musical.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('After the earthquake, Sean Penn brought [BLANK] to the people of Haiti.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Next on ESPN2, the World Series of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('But before I kill you, Mr. Bond, I must show you [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What gives me uncontrollable gas?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What do old people smell like?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The class field trip was completely ruined by [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('When Pharaoh remained unmoved, Moses called down a Plague of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s my secret power?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s there a ton of in heaven?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What would grandma find disturbing, yet oddly charming?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What did the U.S. airdrop to the children of Afghanistan?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What helps Obama unwind?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What did Vin Diesel eat for dinner?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK]: good to the last drop.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Why am I sticky?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What gets better with age?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK]: kid-tested, mother-approved.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s the crustiest?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s Teach for America using to inspire inner city students to succeed?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Studies show that lab rats navigate mazes 50% faster after being exposed to [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Life for American Indians was forever changed when the White Man introduced them to [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Make a haiku.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I do not know with what weapons World War III will be fought, but World War IV will be fought with [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Why do I hurt all over?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What am I giving up for Lent?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In Michael Jackson''s final moments, he thought about [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('When I am President of the United States, I will create the Department of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('When I am a billionaire, I shall erect a 50-foot statue to commemorate [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s my anti-drug?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What never fails to liven up the party?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s the new fad diet?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Major League Baseball has banned [BLANK] for giving players an unfair advantage.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('My plan for world domination begins with [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The CIA now interrogates enemy agents by repeatedly subjecting them to [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In Rome, there are whisperings that the Vatican has a secret room devoted to [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Science will never explain [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('When all else fails, I can always masturbate to [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I learned the hard way that you can''t cheer up a grieving friend with [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The socialist governments of Scandinavia have declared that access to [BLANK] is a basic human right.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In his new self-produced album, Kanye West raps over the sounds of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s the gift that keeps on giving?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Next season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only [BLANK] and his wits.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('When I pooped, what came out of my butt?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In the distant future, historians will agree that [BLANK] marked the beginning of America''s decline.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What has been making life difficult at the nudist colony?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('And I would have gotten away with it, too, if it hadn''t been for [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What brought the orgy to a grinding halt?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('During his midlife crisis, my dad got really into [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('My new favorite porn star is Joey "[BLANK]" McGee.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Before I run for president, I must destroy all evidence of my involvement with [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('This is your captain speaking. Fasten your seatbelts and prepare for [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In his newest and most difficult stunt, David Blaine must escape from [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The Five Stages of Grief: denial, anger, bargaining, [BLANK], and acceptance.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Members of New York''s social elite are paying thousands of dollars just to experience [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('This month''s Cosmo: "Spice up your sex life by bringing [BLANK] into the bedroom."');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Little Miss Muffet Sat on a tuffet, Eating her curds and [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('My country, ''tis of thee, sweet land of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('After months of debate, the Occupy Wall Street General Assembly could only agree on "More [BLANK]!"');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Next time on Dr. Phil: How to talk to your child about [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Only two things in life are certain: death and [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Everyone down on the ground! We don''t want to hurt anyone. We''re just here for [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The healing process began when I joined a support group for victims of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The votes are in, and the new high school mascot is [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Charades was ruined for me forever when my mom had to act out [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Tonight on 20/20: What you don''t know about [BLANK] could kill you.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('D&D 4.0 isn''t real D&D because of the [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('It''s a D&D retroclone with [BLANK] added.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Storygames aren''t RPGs because of the [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The Slayer''s Guide to [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Alightment: Chaotic [BLANK]');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('It''s a D&D retroclone with [BLANK] added.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What made the paladin fall? [BLANK]');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The portal leads to the quasi-elemental plane of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The Temple of Elemental [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Pathfinder is basically D&D [BLANK] Edition.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK] : The Storytelling Game.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('People are wondering why Steve Jackson published GURPS [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Linear Fighter, Quadratic [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('You start with 1d4 [BLANK] points.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Back when I was 12 and I was just starting playing D&D, the game had [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Big Eyes, Small [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In the grim darkness of the future there is only [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('My innovative new RPG has a stat for [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('A true gamer has no problem with [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The Deck of Many [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('You are all at a tavern when [BLANK] approach you.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('For the convention I cosplayed as Sailor Moon, except with [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The worst part of Grave of the Fireflies is all the [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In the Evangelion remake, Shinji has to deal with [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Worst anime convention purchase ever? [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('While powering up Vegeta screamed, [BLANK]!');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('You evaded my [BLANK] attack. Most impressive.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The magical girl found out that the Power of Love is useless against [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The Japanese government has spent billions of yen researching [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK] is Best Pony.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The [BLANK] of Haruhi Suzumiya.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The new thing in Akihabara is fetish cafes where you can see girls dressed up as [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Your drill can pierce [BLANK]!');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Avatar: The Last [BLANK] bender.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In the name of [BLANK] Sailor Moon will punish you!');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('No harem anime is complete without [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('My boyfriend''s a [BLANK] now.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK].tumblr.com');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Somehow they made a cute mascot girl out of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Haruko hit Naoto in the head with her bass guitar and [BLANK] came out.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('After blacking out during New year''s Eve, I was awoken by [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('This holiday season, Tim Allen must overcome his fear of [BLANK] to save Christmas.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Jesus is [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Every Christmas, my uncle gets drunk and tells the story about [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What keeps me warm during the cold, cold, winter?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('On the third day of Christmas, my true love gave to me: three French hens, two turtle doves, and [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Wake up, America. Christmas is under attack by secular liberals and their [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('We got the third rope, now where''s the fourth?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Tackle, Dropdown, [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Christopher Daniels is late on his [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Genius is 10% inspiration, 90% [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The best thing I ever got for Christmas was [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('There''s no crying in [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Mastodon! Pterodactyl! Triceratops! Sabretooth Tiger! [BLANK]!');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Don''t eat the [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('SOOOOO hot, want to touch the [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Stop looking at me [BLANK]!');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I''m cuckoo for [BLANK] puffs.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Silly rabbit, [BLANK] are for kids.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Between love and madness lies [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Instead of chess, the Grim Reaper now gambles for your soul with a game of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Why is my throat sore?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I’m very sorry Mrs. Smith, but Little Billy has tested positive for [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Instead of beating them, Chris Brown now does [BLANK] to women.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Instead of cutting, trendy young emo girls now engage in [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The definition of rock bottom is gambling away [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The Mayan prophecies really heralded the coming of [BLANK] in 2012.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('When I was 10 I wrote to Santa wishing for [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Where or How I met my last signifigant other: [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK], Never leave home without it.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK]. This is my fetish.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I did [BLANK] so you don''t have to!');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I need your clothes, your bike, and [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In a new Cold War retro movie, the red menace tries to conquer the world through the cunning use of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('My zombie survival kit includes food, water, and [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The way to a man''s heart is through [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What was the theme of my second wedding?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What''s the newest Japanese craze to head West?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Everybody loves [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I can only express myself through [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('My new porn DVD was completely ruined by the inclusion of [BLANK]');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The latest horrifying school shooting was inspired by [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I got fired because of my not-so-secret obsession over [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('My new favourite sexual position is [BLANK]');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('A successful job interview begins with a firm handshake and ends with [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Lovin'' you is easy ''cause you''re [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('The blind date was going horribly until we discovered our shared interest in [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK]. Awesome in theory, kind of a mess in practice.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I''m not like the rest of you. I''m too rich and busy for [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('In the seventh circle of Hell, sinners must endure [BLANK] for all eternity.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('What left this stain on my couch?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Call the law offices of Goldstein & Goldstein, because no one should have to tolerate [BLANK] in the workplace.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Turns out that [BLANK]-Man was neither the hero we needed nor wanted.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('As part of his daily regimen, Anderson Cooper sets aside 15 minutes for [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Money can''t buy me love, but it can buy me [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('And what did you bring for show and tell?');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('During high school, I never really fit in until I found [BLANK] club.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Hey, baby, come back to my place and I''ll show you [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Finally! A service that delivers [BLANK] right to your door.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('My gym teacher got fired for adding [BLANK] to the obstacle course.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('As part of his contract, Prince won''t perform without [BLANK] in his dressing room.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('It''s only [BLANK] if you get caught!');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK]: The Next Generation');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Terminator 4: [BLANK]');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Disney presents [BLANK] on ice!');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK]. The other white meat.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('I love the smell of [BLANK] in the morning.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('You''re not gonna believe this, but [BLANK].');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK]. All the cool kids are doing it.');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('Baskin Robbins just added a 32nd flavor: [BLANK]!');
INSERT INTO APP.CARDBLACKCARD ("bcQuestionText") VALUES ('[BLANK] ain''t nothin'' to fuck wit''!');
