INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Flying sex snakes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Michelle Obama''s arms.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('German dungeon porn.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('White people.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Getting so angry that you pop a boner.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tasteful sideboob.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Praying the gay away.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Two midgets shitting into a bucket.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('MechaHitler.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Being a motherfucking sorcerer.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A disappointing birthday party.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Puppies!');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A windmill full of corpses.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Guys who don''t call.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Racially-biased SAT questions.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dying.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Steven Hawking talking dirty.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Being on fire.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A lifetime of sadness.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An erection that lasts longer than four hours.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('AIDS');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Same-sex ice dancing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Glenn Beck catching his scrotum on a curtain hook.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Rapture.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pterodactyl eggs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Crippling debt.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Eugenics.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Exchanging pleasantries.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dying of dysentery.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Roofies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Getting naked and watching Nickelodeon.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The forbidden fruit.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Republicans.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Big Bang.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Anal beads.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Amputees.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Men.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Surprise sex!');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Kim Jong-il.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Concealing a boner');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Agriculture.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Glenn Beck being harried by a swarm of buzzards.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Making a pouty face.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A salty surprise.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Jews.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Charisma.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('YOU MUST CONSTRUCT ADDITIONAL PYLONS.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Panda sex.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Taking off your shirt.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A drive-by shooting.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ronald Reagan.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Morgan Freeman''s voice.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Breaking out into song and dance.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jewish fraternities.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dead babies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Masturbation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hormone injections.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('All-you-can-eat shrimp for $4.99.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Incest.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Scalping.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Soup that is too hot.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The &Uuml;bermensch.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nazis.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tom Cruise.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Stifling a giggle at the mention of Hutus and Tutsis.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Edible underpants.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Hustle.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A Super Soaker&trade; full of cat pee.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Figgy pudding.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Object permanence.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Consultants.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Intelligent design.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nocturnal emissions.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Uppercuts.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Being marginalized.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The profoundly handicapped.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Obesity.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Chutzpah.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Unfathomable stupidity.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Repression.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Attitude.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Passable transvestites.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Party poopers.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The American Dream');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Child beauty pageants.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Puberty.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Testicular torsion.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The folly of man.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nickelback.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Swooping.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Goats eating cans.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The KKK.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Kamikaze pilots.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Horrifying laser hair removal accidents.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Adderall&trade;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A look-see.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Doing the right thing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The taint; the grundle; the fleshy fun-bridge.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lactation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pabst Blue Ribbon.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Powerful thighs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Saxophone solos.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The gays.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A middle-aged man on roller skates.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A foul mouth.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The thing that electrocutes your abs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Heteronormativity.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cuddling.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Coat hanger abortions.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A big hoopla about nothing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Boogers.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A hot mess.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Raptor attacks.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My collection of high-tech sex toys.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fear itself.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('<i>Bees?</i>');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Getting drunk on mouthwash.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sniffing glue.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Oversized lollipops.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An icepick lobotomy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Being rich.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Friends with benefits.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Teaching a robot to love.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Women''s suffrage.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Me time.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The heart of a child.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Smallpox blankets.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The clitoris.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('John Wilkes Booth.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The glass ceiling.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sarah Palin.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sexy pillow fights.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Yeast.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Full frontal nudity.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Parting the Red Sea.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A Bop It&trade;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Michael Jackson.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Team-building exercises.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Harry Potter erotica.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Authentic Mexican cuisine.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Frolicking.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sexting.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Grandma.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Not giving a shit about the Third World.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Licking things to claim them as your own.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Genghis Khan.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The hardworking Mexican.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('RoboCop.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My relationship status.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Scrubbing under the folds.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Porn Stars.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Horse meat.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sunshine and rainbows.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Expecting a burp and vomiting on the floor.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Barack Obama.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Spontaneous human combustion.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Natural selection.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Mouth herpes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Flash flooding.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Goblins.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A monkey smoking a cigar.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Spectacular abs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A good sniff.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Wiping her butt.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Three-Fifths compromise.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pedophiles.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Doin'' it in the butt.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Being fabulous.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Mathletes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Wearing underwear inside-out to avoid doing laundry.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nipple blades.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An M. Night Shyamalan plot twist.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A bag of magic beans.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Vigorous jazz hands.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A defective condom.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Skeletor.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Vikings.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Leaving an awkward voicemail.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Teenage pregnancy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dead parents.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hot cheese.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My sex life.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A mopey zoo lion.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Assless chaps.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Riding off into the sunset.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lance Armstrong''s missing testicle.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sweet, sweet vengeance.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Genital piercings.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Keg stands.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Darth Vader.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Viagra&copy;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Necrophilia.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A really cool hat.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Toni Morrison''s vagina.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An Oedipus complex.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Tempur-Pedic&copy; Swedish Sleep System&trade;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Preteens.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dick fingers.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A cooler full of organs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Shapeshifters.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Care Bear Stare.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Erectile dysfunction.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Keanu Reeves.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Virginia Tech Massacre.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Underground Railroad.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The chronic.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Queefing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Heartwarming orphans.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A thermonuclear detonation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cheating in the Special Olympics.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tangled Slinkys.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A moment of silence.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Civilian casualties.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Catapults.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sharing needles.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ethnic cleansing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Emotions.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Children on leashes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Balls.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Homeless people.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Eating all of the cookies before the AIDS bake-sale.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Old-people smell.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Farting and walking away.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The inevitable heat death of the universe.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The violation of our most basic human rights.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fingering.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The placenta.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Rev. Dr. Martin Luther King, Jr.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Leprosy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sperm whales.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Multiple stab wounds.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Flightless birds.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Grave robbing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Home video of Oprah sobbing into a Lean Cuisine&copy;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Oompa-Loompas.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A murder most foul.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tentacle porn.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Daddy issues.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bill Nye the Science Guy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Peeing a little bit.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The miracle of childbirth.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tweeting.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Another goddamn vampire movie.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Britney Spears at 55.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('New Age music.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Make-A-Wish&reg; Foundation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Firing a rifle into the air while balls deep in a squealing hog.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Active listening.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nicolas Cage.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('72 virgins.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Stranger danger.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hope.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A gassy antelope.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('BATMAN!!!');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Chivalry.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Passing a kidney stone.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Black people.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Natalie Portman.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A mime having a stroke.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Classist undertones.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sean Penn.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A mating display.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Holy Bible.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hot Pockets&copy;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A sad handjob.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pulling out.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Serfdom.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pixelated bukkake.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dropping a chandelier on your enemies and riding the rope up.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jew-fros.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Waiting ''til marriage.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Euphoria&trade; by Calvin Klein.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The World of Warcraft.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lunchables&trade;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Kool-Aid Man.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Trail of Tears.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Self-loathing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A falcon with a cap on its head.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Historically black colleges.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Not reciprocating oral sex.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Global warming.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ghosts.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('World peace.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A can of whoop-ass.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Dance of the Sugar Plum Fairy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A zesty breakfast burrito.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Switching to Geico&reg;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Aaron Burr.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Picking up girls at the abortion clinic.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Land mines.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Former President George W. Bush.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Geese.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Mutually-assured destruction.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('College.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Date rape.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bling.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A gentle caress of the inner thigh.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A time travel paradox.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Seppuku.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Poor life choices.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Waking up half-naked in a Denny''s parking lot.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Italians.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('GoGurt&reg;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Finger painting.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Robert Downey, Jr.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My soul.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Smegma.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Embryonic stem cells.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The South.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Christopher Walken.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gloryholes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pretending to care.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Public ridicule.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A tiny horse.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Arnold Schwarzenegger.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A stray pube.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jerking off into a pool of children''s tears.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Child abuse.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Menstruation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A sassy black woman.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Re-gifting.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Penis envy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A sausage festival.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Getting really high.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Drinking alone.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Too much hair gel.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hulk Hogan.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Overcompensation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Foreskin.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Free samples.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Shaquille O''Neal''s acting career.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Five-Dollar Footlongs&trade;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Whipping it out.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A snapping turtle biting the tip of your penis.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Muhammad (Praise Be Unto Him).');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Half-assed foreplay.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dental dams.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Being a dick to children.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Famine.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Chainsaws for hands.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A gypsy curse.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('AXE Body Spray.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Force.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Explosions.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cybernetic enhancements.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Customer service representatives.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('White privilege.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gandhi.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Road head.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('God.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Poorly-timed Holocaust jokes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('8 oz. of sweet Mexican black-tar heroin.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Judge Judy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Little Engine That Could.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Altar boys.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Mr. Clean, right behind you.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Vehicular manslaughter.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dwarf tossing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Friction.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lady Gaga.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Scientology.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Justin Bieber.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A death ray.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Vigilante justice.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Pope.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A sea of troubles.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Alcoholism.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Poor people.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A fetus.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Women in yogurt commercials.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Exactly what you''d expect.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Flesh-eating bacteria.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My genitals.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A balanced breakfast.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dick Cheney.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lockjaw.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Natural male enhancement.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Take-backsies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Winking at old people.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Opposable thumbs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Flying sex snakes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Passive-aggressive Post-it notes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Inappropriate yodeling.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Golden showers.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Racism.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Copping a feel.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Auschwitz.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Elderly Japanese men.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Raping and pillaging.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Kids with ass cancer.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pictures of boobs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The homosexual agenda.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A homoerotic volleyball montage.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sexual tension.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hurricane Katrina.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fiery poops.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Science.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dry heaving.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cards Against Humanity.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fancy Feast&copy;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A bleached asshole.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lumberjack fantasies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('American Gladiators.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Autocannibalism.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sean Connery.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('William Shatner.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Domino''s&trade; Oreo&trade; Dessert Pizza.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An asymmetric boob job.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Centaurs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A micropenis.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Asians who aren''t good at math.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The milk man.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Waterboarding.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Wifely duties.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Loose lips.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Blood of Christ.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Actually taking candy from a baby.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The token minority.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jibber-jabber.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A brain tumor.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bingeing and purging.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A clandestine butt scratch.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Chinese gymnastics team.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Prancing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Hamburglar.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Police brutality.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Man meat.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Forgetting the Alamo.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Eating the last known bison.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Crystal meth.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Booby-trapping the house to foil burglars.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My inner demons.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Third base.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Soiling oneself.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Laying an egg.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Giving 110%.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hot people.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Friendly fire.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Count Chocula.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pac-Man uncontrollably guzzling cum.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Estrogen.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My vagina.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Kanye West.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A robust mongoloid.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Donald Trump Seal of Approval&trade;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The true meaning of Christmas.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Her Royal Highness, Queen Elizabeth II.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An honest cop with nothing left to lose.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Feeding Rosie O''Donnell.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Amish.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The terrorists.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('When you fart and a little bit comes out.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pooping back and forth. Forever.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Friends who eat all the snacks.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cockfights.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bitches.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Seduction.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A big black dick.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A beached whale.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A bloody pacifier.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A crappy little hand.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A low standard of living.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A nuanced critique.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Panty raids.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A passionate Latino lover.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A rival dojo.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A web of lies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A woman scorned.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Clams.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Apologizing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A plunger to the face.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Neil Patrick Harris.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Beating your wives.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Being a dinosaur.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Shaft.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bosnian chicken farmers.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nubile slave boys.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Carnies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Coughing into a vagina.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Suicidal thoughts.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The ooze.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Deflowering the princess.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dorito breath.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Eating an albino.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Enormous Scandinavian women.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fabricating statistics.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Finding a skeleton.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gandalf.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Genetically engineered super-soldiers.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('George Clooney''s musk.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Getting abducted by Peter Pan.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Getting in her pants, politely.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gladiatorial combat.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Clenched butt cheeks.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hipsters.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Historical revisionism.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Insatiable bloodlust.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jafar.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jean-Claude Van Damme.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Just the tip.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Mad hacky-sack skills.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Leveling up.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Literally eating shit.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Making the penises kiss.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('24-hour media coverage.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Medieval Times&copy; Dinner & Tournament.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Moral ambiguity.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My machete.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('One thousand Slim Jims.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ominous background music.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Overpowering your father.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Stockholm Syndrome.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Quiche.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Quivering jowls.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Revenge fucking.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ripping into a man''s chest and pulling out his still-beating heart.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ryan Gosling riding in on a white horse.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Santa Claus.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Scrotum tickling.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sexual humiliation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sexy Siamese twins.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Saliva.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Space muffins.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Statistically validated stereotypes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sudden Poop Explosion Disease.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The boners of the elderly.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The economy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Syphilitic insanity.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Gulags.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The harsh light of day.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The hiccups.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The shambling corpse of Larry King.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The four arms of Vishnu.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Being a busy adult with many important things to do.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tripping balls.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Words, words, words.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Zeus''s sexual appetites.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A bigger, blacker dick.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The mere concept of Applebee''s&reg;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A sad fat dragon with no friends.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Catastrophic urethral trauma.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hillary Clinton''s death stare.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Existing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A pinata full of scorpions.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Mooing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Swiftly achieving orgasm.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Daddy''s belt.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Double penetration.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Weapons-grade plutonium.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Some really fucked-up shit.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Subduing a grizzly bear and making her your wife.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Rising from the grave.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The mixing of the races.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Taking a man''s eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Scrotal frostbite.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('All of this blood.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Loki, the trickster god.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Whining like a little bitch.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pumping out a baby every nine months.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tongue.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Finding Waldo.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Upgrading homeless people to mobile hotspots.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Wearing an octopus for a hat.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An unhinged ferris wheel rolling toward the sea.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Living in a trashcan.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The corporations.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A magic hippie love cloud.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fuck Mountain.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Survivor''s guilt.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Me.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Getting hilariously gang-banged by the Blue Man Group.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jeff Goldblum.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Making a friend.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A soulful rendition of &#34;Ol'' Man River.&#34;');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Intimacy problems.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A sweaty, panting leather daddy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Spring break!');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Being awesome at sex.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dining with cardboard cutouts of the cast of &#34;Friends.&#34;');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Another shot of morphine.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Beefin'' over turf.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A squadron of moles wearing aviator goggles.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bullshit.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Google.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pretty Pretty Princess Dress-Up Board Game&#174;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The new Radiohead album.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An army of skeletons.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A man in yoga pants with a ponytail and feather earrings.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Mild autism.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nunchuck moves.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Whipping a disobedient slave.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An ether-soaked rag.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A sweet spaceship.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A 55-gallon drum of lube.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Special musical guest, Cher.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The human body.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Boris the Soviet Love Hammer.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The grey nutrient broth that sustains Mitt Romney.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tiny nipples.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Power.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Oncoming traffic.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A dollop of sour cream.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A slightly shittier parallel universe.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My first kill.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Graphic violence, adult language, and some sexual content.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fetal alcohol syndrome.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The day the birds attacked.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('One Ring to rule them all.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Grandpa''s ashes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Basic human decency.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A Burmese tiger pit.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Death by Steven Seagal');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dragon boobs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Verisimilitude.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dissociated mechanics.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Rape.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Storygames.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Random chargen');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('RPG.net.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dice inserted somewhere painful.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('FATAL.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ron Edwards'' brain damage.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Boob plate armor.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gamer chicks.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('GNS theory.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Drizzt.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The entire Palladium Books&reg; Megaverse&trade;');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('BadWrongFun.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Misogynerds.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cultural Marxism.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pissing on Gary Gygax''s grave.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Steve Jackson''s beard.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Natural 20.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Rapenards.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Crisis of Treachery&trade;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Game balance.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fishmalks.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A kick to the dicebags.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bearded dwarven women.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Owlbear''s tears.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Magic missile.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('THAC0.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bigby''s Groping Hands.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Drow blackface.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Save or die.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Swine.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Forge.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Healing Surges.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gelatinous Cubes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Total Party Kill.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Quoting Monty Python.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dumbed down shit for ADD WoW babies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Mike Mearls.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Comeliness.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Vampire: The Masquerade.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Rifts&trade;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The random prostitute table.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dildo of Enlightenment +2');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Grognards Against Humanity.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cthulhu.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The naked succubus in the Monster Manual.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Role-playing and roll-playing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fun Tyrant.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('4rries.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Martial dailies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Black Tokyo.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Killfuck Soulshitter.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cheetoism.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Grimdark.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Kobolds.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Oozemaster.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Rocks fall, everyone dies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Mark Rein&middot;Hagen.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Maid RPG.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Splugorth blind warrior women.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dying during chargen.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Slaughtering innocent orc children.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lesbian stripper ninjas.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Magical tea party.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Grinding levels.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dice animism.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('White privilege.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Githyanki therapy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Amber Diceless Roleplaying.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A ratcatcher with a small but vicious dog.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bribing the GM with sexual favors.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Eurocentric fantasy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sacred cows.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gygaxian naturalism.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Special snowflakes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Neckbeards.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gazebos.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lorraine Williams.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nude larping.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Portable holes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Steampunk bullshit.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dump stats.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ale and whores.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Japanese schoolgirl porn.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Horny catgirls.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Japanese people.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cimo.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('ZA WARUDO!');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('40 gigs of lolicon.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Goku''s hair.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Slashfic.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Star Gentle Uterus');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Naruto headbands.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Homestuck troll horns.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hayao Miyazaki.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The tsunami.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Death Note.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Small breasts.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Asians being racist against each other.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Weeaboo bullshit.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tsundere.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Body pillows.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A lifelike silicone love doll.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Anime figures drenched in jizz.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Surprise sex.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Yaoi.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Girls with glasses.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bronies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Blue and white striped panties.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('4chan.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hello Kitty vibrator.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Finishing attack.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Keikaku* *(keikaku means plan).');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hatsune Miku''s screams.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('School swimsuits.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lovingly animated bouncing boobs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dragon Balls.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Zangief''s chest hair.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('DeviantArt.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Giant fucking robots.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Crossplay.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Moeblob.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Carl Macek''s rotting corpse.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My waifu.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Voice actress Megumi Hayashibara.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lynn Minmei.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Panty shots.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Love and Justice.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Consensual tentacle rape.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gundam.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Captain Bright slapping Amuro.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Wave Undulation Cannon.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Having sex in the P.E. equipment shed.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tainted sushi.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Shitty eurobeat music.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bad dubbing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fangirls.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Kawaii desu uguu.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Futanari.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lesbian schoolgirls.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Osamu Tezuka, rolling in his grave forever.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('FUNimation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Underage cosplayers in bondage gear.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jackie Chan.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Exchanging Pocky for sexual favors.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Shipping.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Chiyo''s father.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Magikarp.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Derpy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nanoha and her special friend Fate.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The marbles from Ramune bottles.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Wideface.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Spoilers.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Man-Faye.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Oppai mousepads.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Another dimension.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Homura sniffing Madoka''s panties.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hadouken.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Asian ball-jointed dolls.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('J-list.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Childhood friends.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Monkey D. Luffy''s rubbery cock.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cloud''s giant fucking Buster Swords.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Taking a dump in Char''s helmet.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hentai marathons.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gothic Lolita.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Onaholes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Super Saiyan Level 2.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gaia Online.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Santa''s heavy sack.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Clearing a bloody path through Walmart with a scimitar.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Another shitty year.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Whatever Kwanzaa is supposed to be about.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A Christmas stocking full of coleslaw.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Elf cum.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The tiny, calloused hands of the Chinese children that made this card.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Taking down Santa with a surface-to-air missile.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Socks.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pretending to be happy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Krampus, the Austrian Christmas monster.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Star Wars Holiday Special.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My hot cousin.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Mall Santa.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Several intertwining love stories featuring Hugh Grant.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A Hungry-Man&trade; Frozen Christmas Dinner for one.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gift-wrapping a live hamster.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Space Jam on VHS.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Immaculate conception.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fucking up ''Silent Night'' in front of 300 parents.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A visually arresting turtleneck.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A toxic family environment.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Eating an entire snowman.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bumpses.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A Vin Gerard H8 X 10.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Harry Acropolis.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Under the ring.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Afa The Wild Samoan.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Peanut Butter and Baby sandwiches.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Yard Tards.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Two girls, one cup.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ugly Mexican Hookers.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Duct tape.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sodaj.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Steve The Teacher.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jefferee.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Autoerotic Asphyxiation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sonic The Hedgehog.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lotto Money.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jailbait.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Prison rape.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Two And A Half Men.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Anne Frank.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Black Santa.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jesus Christ (our lord and saviour).');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Farting with your armpits.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Poopsicles.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Slaughtering innocent children.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sex with vegetables.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My gay ex-husband.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Accidentally sexting your mom.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tabasco in your pee-hole.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pee Wee Herman.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A breath of fresh air.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A great big floppy donkey dick.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A pyramid scheme.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A school bus surrounded by cop cars.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A short walk in the desert with shovels.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('All the boys staring at your chest.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An amorous stallion.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Being so wet it just slides out of you.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Being tarred and feathered.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Catching ''em all.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Chained to the bed and whipped to orgasmic bliss by a leather-clad woman.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Child-bearing hips.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Defenestration.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dungeons and/or dragons.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ecco the Dolphin.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('George Washington riding on a giant eagle.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Getting abducted and probed by aliens.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Going viral on YouTube.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gushing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Making the baby Jesus cry.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('More than you can chew.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Napalm.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pancake bitches.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Playing God with the power of lightning.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Playing tonsil-hockey.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Racing cheese wheels downhill.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Riding the bomb.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Settling arguments with dance-offs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sheer spite.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sinister laughter.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('SS Girls.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Stealing your sister''s underwear.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Stroking a cat the wrong way.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sucking and blowing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The bullet with your name on it.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The entire rest of eternity, spent in fucking Bruges.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The oceans rising to reclaim the land.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A cocained-fuelled sex orgy heart attack.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A cocktail umbrella ');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A murder/suicide pact.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A squirming mass of kittens.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An angry mob with torches and pitchforks.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Biting my girlfriend like a vampire during sex.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dropping your pants and saluting.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Frankenstein''s Monster');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Getting a blowjob in a theater.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Going full retard.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Going slob-slob-slob all over that knob.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Leaking implants.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Low-flying planes.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Monkies flinging their own shit.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My robot duplicate.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Other people’s children.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('People who can''t take a joke. Seriously.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Popping a boner during Sex Ed class.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Projectile vomiting.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Pulling down panties with your teeth.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Saying ');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Shedding skin like a snake.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Shooting Valley Girls for like, saying like all the time. Really.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Slow seductive tentacle rape.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Talking like a pirate, y’arr!');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Tenderly kissing a unicorn''s horn.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('That bastard Jesus!');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The last shreads of dignity.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The power of friendship.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('This card intentionally left blank.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Throwing water on a braless woman in a white t-shirt');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Upskirts.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Wasting all your money on hookers and booze.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Winning.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A foot fetish.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A powerful gag reflex.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A tight, Asian pussy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Explosive decompression.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Extraordinary Rendition.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Forgetting the safety word.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Greeting Christmas carollers naked.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Handcuffs, without the key.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Having a drill for a penis.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hot Jailbait Ass.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Liposuction gone horrible wrong.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My harem of scantily clad women.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nazi Zombie Robot Ninjas.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Redneck gypsies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Scissoring.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A guy and two robots who won’t shut up.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A shotgun wedding.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Anne Frank''s diary');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Autoerotic asphyxiation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Blow Up Bianca the Latex Lovedoll.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Endlessly tumbling down an up escalator.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fun with nuns.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Getting it all over the walls.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Holiday Dinner by Jack Daniels.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nailgun fights.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Teaching the bitch a lesson.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nazi super science.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Making a human centipede.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The primal, ball-slapping sex your parents are having right now.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A cat video so cute that your eyes roll back and your spine slides out of your anus.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cock.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A cop who is also a dog.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dying alone and in pain.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Gay aliens.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The way white people is.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Reverse cowgirl.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Quesadilla Explosion Salad&trade; from Chili''s&copy;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Actually getting shot, for real.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Not having sex.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Vietnam flashbacks.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Running naked through a mall, pissing and shitting everywhere.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Nothing.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Warm, velvety muppet sex.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Self-flagellation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The systematic destruction of an entire people and their way of life.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Samuel L. Jackson.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A boo-boo.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Going around punching people.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The entire Internet.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Some kind of bird-man.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Chugging a lava lamp.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Having sex on top of a pizza.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Indescribable loneliness.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An ass disaster.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Shutting the fuck up.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('All my friends dying.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Putting an entire peanut butter and jelly sandwich into the VCR.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Spending lots of money.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Some douche with an acoustic guitar.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Flying robots that kill people.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A greased-up Matthew McConaughey.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An unstoppable wave of fire ants.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Not contributing to society in any meaningful way.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An all-midget production of Shakespeare''s Richard III.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Screaming like a maniac.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The moist, demanding chasm of his mouth.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Filling every orifice with butterscotch pudding.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Unlimited soup, salad, and breadsticks.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Crying into the pages of Sylvia Plath.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Velcro&trade;.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A PowerPoint presentation.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A surprising amount of hair.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Eating Tom Selleck''s mustache to gain his powers.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Roland the Farter, flatulist to the king.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('That ass.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A pile of squirming bodies.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Buying the right pants to be cool.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Blood farts.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Three months in the hole.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A botched circumcision.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Land of Chocolate.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Slapping a racist old lady.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A lamprey swimming up the toilet and latching onto your taint.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jumping out at people.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A black male in his early 20s, last seen wearing a hoodie.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Mufasa''s death scene.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Bill Clinton, naked on a bearskin rug with a saxophone.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Demonic possession.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Harlem Globetrotters.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Vomiting mid-blowjob.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My manservant, Claude.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Having shotguns for legs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Letting everyone down.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A spontaneous conga line.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A vagina that leads to another dimension.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Disco fever.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Getting your dick stuck in a Chinese finger trap with another dick.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Fisting.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The thin veneer of situational causality that underlies porn.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Girls that always be textin''.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Blowing some dudes in an alley.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Drinking ten 5-hour ENERGYs&reg; to get fifty continuous hours of energy.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Sneezing, farting, and coming at the same time.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A freshly-filled diaper');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Glue');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An unusually-attractive transvestite');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Hand-me-down adult diapers');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A stillborn fetus');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A disgraced pelican');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Three buckets of urine, free for 2 nights, with no late fee');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My testicles');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A black woman''s vagina');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('My asshole');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A whale''s blowhole');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('2 Girls 1 Cup');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('The Big Bang Theory (TV)');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Teen pregnancy');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ass hair');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Vaginal warts');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Ellen Degeneres');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Jews Against Humanity');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Indy wrestling');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Cunt');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Beating a crowd of delightful parents to death with a steel dildo');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Beating a crowd of delightful parents to death with a steel dildo while dressed as Ru Paul''s brother, Ron.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('A roll in the hay');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('"Get ''em, Steve-Dave!"');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('God Hates You');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Manboobs.');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Daniel Benoit');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Vomiting in the shower');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('An intellectually superior overlord');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Dwight Schrute');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Casey Anthony');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Clubbin seals');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Stunt cock');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Anal lice');
INSERT INTO APP.CARDWHITECARD ("wcCardText") VALUES ('Lightsaber Dildos');
